feat: add input component
frontendship/frontendship-website pull request #45
Opened 2023-01-15 11:16 UTC by osmandlsmn

**What was done**

Added react-hook-form for form validation.
Error message will be shown in case of any error.

**What To do**

When the library is added for the icon, an error icon will be added to the input.

2023-01-16 16:00 UTC, oguzergul commented on components/Input/Input.classes.ts
> +    size: {
there is no different text style in our design. why did you need this?

2023-01-16 16:00 UTC, oguzergul commented on components/Input/Input.classes.ts
> +  defaultVariants: {
we don't have different input sizes. why did you need this?

2023-01-16 16:01 UTC, oguzergul commented on components/Input/Input.tsx
> + * @example <Input name="email" label="Email" placeholder="olivia@untitledui.com"  />
we can remove this example from here. we will create the component documents later.

2023-01-16 16:04 UTC, oguzergul commented on components/Input/Input.tsx
> +        <ErrorField name={rest.name} />
Rest is not clear enough to understand what the prop works for. it should be like errorMessage="bla bla bla"
+ you can add onChange prop and can remove spread props

2023-01-16 16:33 UTC, eraygundogmus commented
These are errors that pipeline throwed.

Please fix it.

<img width="1130" alt="Screen Shot 2023-01-16 at 19 32 32" src="https://user-images.githubusercontent.com/74984741/212726665-2036c9ab-38a2-4c87-99a9-d1e48b6f3ad9.png">

2023-01-16 16:33 UTC, eraygundogmus requested changes
pipeline fix

2023-01-17 19:33 UTC, wralith commented on components/Input/Input.classes.ts
> +export default cva(
IMO we don't need `cva` like this too since there are no variants. `cx` function from `cva` seems better fit to add error css rules conditionally.

2023-01-18 16:02 UTC, oguzergul commented on components/Input/Input.classes.ts
> +export default cva(
@osmandlsmn make the last changes and I will merge it. If there is no component variant you can directly use styles. it is up to you.

2023-01-18 16:22 UTC, eraygundogmus approved these changes

2023-01-19 00:47 UTC, osmandlsmn commented
**What was done**

I used `cx` instead of `cva` as @wralith said.
Removed `input.classes.ts`.

**Example Usage**

```ts
<Input label="Email" placeholder="olivia@untitledui.com" />
<Input label="Email" placeholder="olivia@untitledui.com" errorMessage="bla bla bla" />
<Input label="Email" placeholder="olivia@untitledui.com" disabled />

2023-01-20 08:28 UTC, oguzergul approved these changes

2023-01-20 08:28 UTC, merged