feat: add blog post card component
frontendship/frontendship-website pull request #49
Opened 2023-01-18 22:38 UTC by seymenklc

What was done

added arrow upright icon 
created blog post card without labels

What To do; label component will be added

2023-01-19 08:56 UTC, eraygundogmus requested changes

2023-01-19 08:56 UTC, eraygundogmus commented on components/Blog/Card/index.tsx
> +// TODO: Add Card Labels
we can remomve that, as @oguzergul said, there will be a docs for components soon

2023-01-19 08:56 UTC, eraygundogmus commented on components/Blog/Card/Info.tsx
> +         <span>{children[0]}</span>
it does not seem like a healty way to do that, is not it kinda over engineering?

2023-01-19 08:56 UTC, eraygundogmus commented on components/Blog/Card/Title.tsx
> +         <h3 className="text-2xl font-semibold text-gray-900">{children}</h3>
what happens if I click on this title? is not it better to routing on text too like an anchor tag?

2023-01-20 00:00 UTC, oguzergul requested changes

2023-01-20 00:00 UTC, oguzergul commented on components/Blog/Card/Title.tsx
> +            <Image
You should not use svgs as Image. Svg is not an image type. It is vector. Please use svg component library which already installed to projrct named as react-feather. Or you can add new svg icons and use with svgr.

2023-01-20 00:00 UTC, oguzergul commented on components/Blog/Card/index.tsx
> +const Card = ({ children }: Props) => {
This component is specific for Blog. Component name should be BlogCard.

2023-01-20 00:00 UTC, oguzergul commented on components/Blog/Card/Img.tsx
> +const Img = ({ ...props }: Props) => {
We dont need to divide BlogCard into seperate components. You can use Compound Component Pattern for createing it more simple way. Create only BlogCard file and implement all componnents into this file. And delete all other files.You can learn it by watching this video or you can inspect codes on this repository. https://youtu.be/4xFf_KiBE6A

2023-01-20 00:50 UTC, closed without merging