feat: add social share buttons
frontendship/frontendship-website pull request #51
Opened 2023-01-19 15:26 UTC by wralith

#32  

*Installs `react-share` external dependency*

### Potential Additions
- `url` property might have default value that points current page url. 
  - It requires domain name from environment variable or some sort of context. `useRouter` only provides path.
-  More switches, variants etc. *-there is only one usage in design file-*

2023-01-19 15:55 UTC, eraygundogmus requested changes
can we use something [dynamic component](https://www.storyblok.com/tp/react-dynamic-component-from-json)? I can clearly see a repating pattern here

2023-01-19 16:28 UTC, wralith commented
> can we use something [dynamic component](https://www.storyblok.com/tp/react-dynamic-component-from-json)? I can clearly see a repating pattern here

It is not a dynamic content, also each social media platform have different API's and behaviors in regard to share. IMO such implementation would add unnecessary coupling therefore complexity.

e.g. lets say we want to add email too, share via email and share on twitter have different concerns. We might want prepend a paragraph to email, but it is not the case for tweet.

2023-01-19 23:38 UTC, oguzergul requested changes

2023-01-19 23:38 UTC, oguzergul commented on components/SocialShareButtons/index.tsx
> +} from 'react-share';
We dont need to use external library for buttons. These are just buttons that redirect users to related accounts. We can create these components with using Html + Tailwind Css. You should uninstall package.

2023-01-19 23:38 UTC, oguzergul commented on components/SocialShareButtons/index.tsx
> +const SocialShareButtons = ({ title, url }: { title: string; url: string }) => (
ShareButton should be generic. You should create responsive generic social button.

2023-01-19 23:38 UTC, oguzergul commented on components/SocialShareButtons/index.tsx
> +    <button onClick={() => navigator.clipboard.writeText(url)}>
It will navigate to related account. Not copy text.

2023-01-19 23:38 UTC, oguzergul commented on components/SocialShareButtons/index.tsx
> +const SocialIcon = ({ src, alt }: { src: string; alt: string }) => (
You should not use SVGs as an Image. Svg  is a vectoral component. You should use as a Svg. Please use react-feather icons. It is already installed. Or you can setup svgr and use custom svg icons.

2023-01-20 01:47 UTC, wralith commented
Aren't those buttons supposed to share current page in social media platforms, why would a share button redirect to some users profile? 

To clarify, those buttons only appear twice in design file, in blog page part. They used horizontal with same size in both desktop and mobile view. Also, their style does not match with other social media links.

2023-01-23 19:11 UTC, wralith commented
I extracted button to generic `IconButton` component. 
- It has 3 variants: `default` (*svg itself without modifying color or anything*), `gray` and `bordered`. *(gray and bordered done according to style page)*
-  And padding choices. 
### Social Share Button Update
- Social share button now uses `bordered` variant of `IconButton`. 
  - 4 share buttons (copy, twitter, facebook, linkedin)  have their internal logic to produce expected url. 
  - `ShareButtonGroup` component expose each of them wrapped in simple a api, expects `url` and `title` as string. 

Each share button also exported singly *Maybe we can keep them internal to prevent confusion?*

2023-01-24 08:02 UTC, eraygundogmus approved these changes

2023-01-24 15:14 UTC, oguzergul approved these changes

2023-01-24 15:14 UTC, merged