feat: add carousel component and section
frontendship/frontendship-website pull request #54
Opened 2023-01-20 22:19 UTC by osmandlsmn

https://github.com/frontendship/frontendship-website/issues/25 https://github.com/frontendship/frontendship-website/issues/27

- [x] Added swiper js library for slider.
- [x] For the static data in Slider, I created a folder called data and took it from there.
- [x] The section component has also been coded for the comments component.

2023-01-21 08:21 UTC, eraygundogmus requested changes

2023-01-21 08:21 UTC, eraygundogmus commented on data/quotes.ts
> +export interface Quote {
this is a type, so it's better to keep in a type file/folder

2023-01-21 08:21 UTC, eraygundogmus commented on components/Quote/QuoteSlider.tsx
> +export default QuoteSlider;
this seems like a compound component

2023-01-22 10:34 UTC, oguzergul approved these changes

2023-01-22 10:34 UTC, merged